"""Add webhook_processed field to Payment model

Revision ID: 2e99afdbf552
Revises: e177d6c0b9cc
Create Date: 2026-03-06 13:50:43.092215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e99afdbf552'
down_revision: Union[str, None] = 'e177d6c0b9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('webhook_processed', sa.String(), nullable=True))
    op.create_index('ix_gateway_status', 'payments', ['payment_gateway', 'status'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_gateway'), 'payments', ['payment_gateway'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_index('ix_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index('ix_transaction_id', 'payments', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_id', table_name='payments')
    op.drop_index('ix_status_created', table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_gateway'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index('ix_gateway_status', table_name='payments')
    op.drop_column('payments', 'webhook_processed')
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
